// Copyright [2025] [Banana.ch SA - Lugano Switzerland]
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**********************************************************
 * 
 * INVESTMENT ACCOUNTING ERROR MESSAGES HANDLER
 * 
 *********************************************************/

/**
 * 
 * @param {*} errorId 
 * @returns 
 */
function getErrorMessage(errorId) {
    lang = 'en';
    switch (errorId) {
        case "ID_ERR_VERSION_NOTSUPPORTED":
            return "This script is not compatible with your current version of Banana Accounting.\nPlease update to the latest version.";
        case "ID_ERR_LICENSE_NOTVALID":
            return "This extension requires Banana Accounting+ Advanced";
        case "NOT_AVAILABLE_WITH_MULTI_CURRENCY":
            return "This report is only available for accounting files without multi-currency"
    }
    return '';
}

/**
 * 
 * @param {*} errorId 
 * @param {*} missingElement 
 * @param {*} refTable 
 * @returns 
 */
function getErrorMessage_MissingElements(errorId, missingElement) {
    lang = 'en';
    switch (errorId) {
        case "NO_ITEMS_TABLE":
            return "Items table not found";
        case "ASSET_NOT_FOUND": // For a specific asset.
            return "Asset: " + missingElement + " not found in the Items table";
        case "ASSET_WITHOUT_ACCOUNT":
            return "Asset: " + missingElement + " without assigned Asset account";
        case "NO_ASSETS_FOUND": // General, no assets at all.
            return "No Assets found in the Items table";
        case "SELECTED_ROW_NOT_VALID":
            return "The selected row in the Transactions table is not valid";
        case "CHILD_ROW_SELECTED":
            return "The selected row in the Transactions table is not correct"
        case "ASSET_ID_MISSING_IN_ROW":
            return "The selected row does not contain the Asset ID";
        case "QTY_MISSING_IN_ROW":
            return "The selected row does not contain a valid sales Quantity";
        case "UNITPRICE_MISSING_IN_ROW":
            return "The selected row does not contain a valid Unit Price";
        case "AMOUNT_MISSING_IN_ROW":
            return "The selected row does not contain a valid amount";
        case "ASSET_WITHOUT_TYPE":
            return "Asset: " + missingElement + " without assigned type. Define the type in the Items table";
        case "NO_ASSET_ACCOUNTS_FOUND":
            return "No Asset Accounts found in the Items table";
    }
}

/**
 * This function returns the anchor used in the documentation to link the error messages section.
 * We use the same anchor in all the extensions, as for each extension we have an error messages section in the documentation
 * where we describe all the possible error messages that can be generated by the extension.
 * In Drupal we need to define an id for the title of th esection if we want to use it like an anchor.
 * The id of the error messages section title is "error_messages" and is defined in the header tag <h2>.
 * if the id is changed in the documentation, the value returned by this function must be updated accordingly.
 * @returns the id of the error messages section in the documentation
 */
function getErrorMessageReferenceAnchor() {
    return "error_messages";
}